import { Geist, Geist_Mono } from "next/font/google";
import {NextIntlClientProvider} from 'next-intl';
import "./globals.css";
// ui components
import NavBar from "@/components/ui/nav-bar";
import Footer from "@/components/ui/footer";
// context
import ClientThemeWrapper from "@/context/ClientThemeWapper";
import { ThemeProvider } from "@/context/ThemeContext";
import { ToastProvider } from "@/context/ToastContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Resume.AI - Resume Builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      dir="ltr"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <NextIntlClientProvider>
        <ToastProvider>
          <ThemeProvider>
            <ClientThemeWrapper>
              <NavBar />
              {children}
              <Footer />
            </ClientThemeWrapper>
          </ThemeProvider>
        </ToastProvider>
      </NextIntlClientProvider>  
      </body>
    </html>
  );
}
